language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "jwbSd6LpXBA9qKL17ZKSEfxMsqf6n8QbQwbo5FT37CkeCgIkJ46HTAu/m9KfXl//Vh+vIyiinXk973F1X57CKB+M68ATkTEymWbuCALV0XnQEla34wWy2UrdfOgIp/Un6FYsstCPBfTWYBZgVqNLwtq6sKOa+WFa3O+USDMwVWv1Y3j+Pvre3iKFeqX3yBtX9GXvTKzE0SGLSYP11vBeW/5hoxMRE7JmircZdiRuwjIra9dEXJvNfOE2XT5xU5z0ew9sm4iHEw6ylKjJ3DknoZXKos08PJVQg/WlkRf82WPTgwKNHNaeZwVUhlAadz3A1iALbtkg4EhY3SxvFHphiaUnAPcK/pHaSm7YbbZ5jusiP9mZlsZ7DRr1Q6WdEMSJQZ7lMxbRl+e0mHM0L5yZqdKvO6OaTLsGpP5+KWnKzRcP8zWoXoG6cR5fHiiWLLfwkeanKkJs/KlLb4jvJXaoV8PNg1BPuuOvb90WfkvEk815DhSW47BhiyL5yAuKpwJKZqjKjkuAy1ZE+lIeBd/kErSIHACMteH1OQkAYfoSISniOKsM+v2oEd5X2PgU7e8wxcKDfoORZsvPnsCLXHbSGLpQts4z60LFZprgNei9aW5iOhReHsOO354ZImo8SkQWFom2sIt5i8rL2k09euPwoI8OUbJYI4j3FXkL5bf1Cw4="
  api_key: # c900
    secure: "SeJLyYbFsS36SSMPegf2zM6wwuZoWKEPmw6Cw+XipodPUzMRV2iMNInKu/dwD5iigr7LN5bAwlwSCiH3YFwoCucv/EPQFiHktgM0+Gc8zZlxIqBynzMr7wte4ZKXjsztQQwA6fWuOpJa06305EkRnVVdw1wAdDg5BNAGBuCTMH61l3d5MWTb88txhQqKpK5xxAnX6GhF3y0X1XMkyUwB6r0PoIRi84HNb7w3jWJGqH8R3OxC2q8ov+VxyAouPG3+ghTAyLYa/7oyEnSh0E0CBPeCBeM1DaEOKbZdIzC3ysv1nsiDR25d76lT2brFZokD4gYZ3KawIQSZFFpyd5lccd84rpEV1qNAgQzG8u3f7GyDPeiyDD4QK1SX65cBHJU4rzlPLTHLMx8d6XP9joJgYbr/xIVHiFVhKcLsQg0cECwMgQ8DBRLU5Df0yl1+facR2EnF1SBgdiJM2sD8bIHgMZfAFg1IQ6KlGgN515V7D7yqyTpSIi++oWHJ4UUnK6riuPZM9qI4zlKT0CbQ3pmU8FbM21YnHFslnkgbokSoUkBWh1I4n/93jn7TsTcsuR1OYL5LPSO8xnKzOKDj0izH0NE4pzz4d83u+hbe1ejFeMdq5fdpBjMrlBH71OPzI1yrlvgVX4EFK31qErAlETg/hJXGOMeb0ZUiN1iw5z/gwCw="
  on:
    tags: true
    node: lts/*
